### ISSUE TITLE
源码问题

### ISSUE THREAD

**Issue by cgy0905** [maning0303/GankMM#11]
github上的源码里面有一个xml资源文件没有，名称是mn_image_browser_item_show_image2

**Comment by Chenshuai770** [comment]
同样的问题,就是不能编译了

**Comment by maning0303** [comment]
@cgy0905 @Chenshuai770 之前很多Api不能用了导致没有更新，近期很更新一下Api和部分代码。提交了一版，那个资源已经不再使用了。
