### ISSUE TITLE
导入项目一直打不开

### ISSUE THREAD

**Issue by chingHao** [maning0303/GankMM#4]
![image](https://user-images.githubusercontent.com/10030177/27062118-7aa93c8c-501b-11e7-8220-1965e81467c1.png)

**Comment by maning0303** [comment]
这个问题的gradle版本的问题，你可以把项目目录下的gradle/wrapper/gradle-wrapper.properties 这个文件的最后一行（distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip）换成你本地可以打开项目的gradle版本再重新build一下试试！

**Comment by maning0303** [comment]
上面还有问题的话把项目的主build.gradle 里面的也可以换成你本地能运行的项目 ，都是gradle版本的问题   
dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'
}
