### ISSUE TITLE
编译不报错，安装运行时报错

### ISSUE THREAD

**Issue by WinnerLi** [maning0303/GankMM#5]
![image](https://user-images.githubusercontent.com/18546315/34399097-26f66fc0-ebbf-11e7-8a18-3b53d5bc9c7e.png)
![image](https://user-images.githubusercontent.com/18546315/34399108-42d08a78-ebbf-11e7-9f1e-82494cbaea0b.png)

`android:background="?refresh_arrow_icon"`  不懂这种用法什么意思，请指教

**Comment by maning0303** [comment]
@WinnerLi  这个用法是为了夜间模式，报错是因为使用了VectorDrawableCompat，这个...... 你的手机是5.0下的系统吗 ？

**Comment by maning0303** [comment]
@WinnerLi 你试试最新版本，代码最新提交
